#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# Get the PID of the Gunicorn master process
PID=$(ps aux | grep 'gunicorn' | grep 'master' | awk '{print $2}')

# Send the HUP signal to the Gunicorn master process
if [ -n "$PID" ]; then
  kill -HUP $PID
  echo "Sent HUP signal to Gunicorn master process (PID: $PID)"
else
  echo "Gunicorn master process not found"
fi
